### ISSUE TITLE
Does it work in Java 8 + Tomcat 8.5?

### ISSUE THREAD

**Issue by naXa777** [JD-Software/JDeSurvey#14]
When building from sources and deploying to Tomcat 8.5 I get the following errors
```
15-Nov-2018 05:09:30.455 SEVERE [RMI TCP Connection(2)-127.0.0.1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start: 
 org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/admin]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	... and more
Caused by: org.apache.catalina.LifecycleException: Failed to start component [org.apache.catalina.webresources.StandardRoot@d64cd8a]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	... and more
Caused by: org.apache.catalina.LifecycleException: Failed to initialize component [org.apache.catalina.webresources.JarResourceSet@697b57ea]
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:112)
	... and more
Caused by: java.lang.IllegalArgumentException: java.util.zip.ZipException: error in opening zip file
	at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.initInternal(AbstractSingleArchiveResourceSet.java:142)
	... and more
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	... and more

15-Nov-2018 05:09:30.467 SEVERE [RMI TCP Connection(2)-127.0.0.1] org.apache.tomcat.util.modeler.BaseModelMBean.invoke Exception invoking method manageApp
 java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/admin]]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:756)
	... and more
15-Nov-2018 05:09:30.470 SEVERE [RMI TCP Connection(2)-127.0.0.1] org.apache.tomcat.util.modeler.BaseModelMBean.invoke Exception invoking method createStandardContext
 javax.management.RuntimeOperationsException: Exception invoking method manageApp
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:308)
	... and more
Caused by: java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/admin]]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:756)
	... and more

```
I updated pom.xml files to target Java 8 and I still get the same error.

```xml
<artifactId>maven-compiler-plugin</artifactId>
<configuration>
    <source>1.8</source>
    <target>1.8</target>
</configuration>
```

**Comment by the-brickster** [comment]
Im encountering a similar issue on Tomee 1.7.4

**Comment by watsonleeyoung** [comment]
Does anyone have problem logging into the system. I installed it on my computer and try to access it by localhost:8080/admin. It doesn't work. But when I use localhost:8080/survey. It worked. But I cannot login with admin and P@ssword1. Thanks !

**Comment by the-brickster** [comment]
@watsonleeyoung yes, it seems as if the current login solution for JDESurvey does not work. I'm using a custom servlet.

**Comment by watsonleeyoung** [comment]
Thanks man! Is it possible you share more? Cheers!

**Comment by the-brickster** [comment]
The current solution I'm using is a custom inhouse authentication servlet. I hope to get a general authentication servlet running with JDESurvey in the next coming days.

**Comment by watsonleeyoung** [comment]
Wow, cool! Thank you so much for sharing that. Best wishes to your survey research! 
I am wondering if you want to connect on LinkedIn? We are actually looking for a java developer/consultant right now. Thanks!

**Comment by the-brickster** [comment]
As an update Im still trying to get a general login solution, I will need to dig in to the servlet we use inhouse.

**Comment by hypadr1v3** [comment]
Are you able to get the solution? I'm also getting this problem

**Comment by zhangyu007** [comment]
> 我正在使用的当前解决方案是一个自定义内部认证servlet。我希望在未来几天内使用JDESurvey运行一个通用身份验证servlet。

你好，我下载好了源代码，但是不知道怎么运行

**Comment by the-brickster** [comment]
@zhangyu007 you will need an application server like tomcat/tomee to run the generated WAR file.

**Comment by zhangyu007** [comment]
> @ zhangyu007你需要一个像tomcat / tomee这样的应用服务器来运行生成的WAR文件。

用idea生成war文件吗？能不能留下联系方式QQ或者微信，这样很方便

**Comment by zhangyu007** [comment]
> @ zhangyu007你需要一个像tomcat / tomee这样的应用服务器来运行生成的WAR文件。

IDEA生成war文件吗？能不能留下联系方式QQ或者微信？

**Comment by zhangyu007** [comment]
> @ zhangyu007你需要一个像tomcat / tomee这样的应用服务器来运行生成的WAR文件。

IDEA生成WAR文件吗？能不能留下联系方式QQ或者微信？

**Comment by the-brickster** [comment]
@zhangyu007 Which maven command did you run to build the project? Are you using Window or Linux?

**Comment by zhangyu007** [comment]
> @ zhangyu007您为构建项目运行了哪个maven命令？你在使用Window还是Linux？

使用Window，IDEA导入源文件然后怎么用tomcat启动运行

**Comment by zhangyu007** [comment]
> @ zhangyu007您为构建项目运行了哪个maven命令？你在使用Window还是Linux？

使用WINDOWS，IDEA导入源文件然后怎么用Tomcat的启动运行

**Comment by NewSNode** [comment]
大家好，我没找到数据库建表语句，只有数据初始化脚本，谁知道建表脚本在哪里吗？

**Comment by NewSNode** [comment]
> 
> 
> @watsonleeyoung yes, it seems as if the current login solution for JDESurvey does not work. I'm using a custom servlet.

would you give the create table scripts for me. thank you very much

**Comment by NewSNode** [comment]
oooh, i gat it ,the table well auto created at the server started.

**Comment by cvanslyke** [comment]
> Does anyone have problem logging into the system. I installed it on my computer and try to access it by localhost:8080/admin. It doesn't work. But when I use localhost:8080/survey. It worked. But I cannot login with admin and P@ssword1. Thanks !

I'm having this same issue. I cannot use the application. I followed the installation instructions thinking this would be easy, but I cannot access the /admin page. I get a 500 error. I can however hit the /surveys page and it gives me a login screen but the default username/password used in the installation tutorial don't seem to work here.

**Comment by xinglongMedical** [comment]
> 
> 
> oooh, i gat it ,the table well auto created at the server started.



> the default username/password

where to find the default username/password ? i'm deploying the project in a tomcat ,and it's run well ,but i can't find the password to login .
