### ISSUE TITLE
Tried to create survey definition from admin 

### ISSUE THREAD

**Issue by ghost** [JD-Software/JDeSurvey#5]
javax.servlet.jsp.JspTagException: No message found under code 'isAutoReminderEnabled_tip' for locale 'en_US'.
    at org.springframework.web.servlet.tags.MessageTag.doStartTagInternal(MessageTag.java:184)
    at org.springframework.web.servlet.tags.RequestContextAwareTag.doStartTag(RequestContextAwareTag.java:79)
    at org.apache.jsp.WEB_002dINF.views.settings.surveyDefinitions.create_jspx._jspx_meth_spring_005fmessage_005f29(create_jspx.java:1862)

**Comment by skommaSFDC** [comment]
I got the same error when I tried to create a survey both as admin and an internal user:  ERROR 2017-05-26 11:30:31,063 [http-apr-8080-exec-4] (org.springframework.web.servlet.tags.RequestContextAwareTag:82) [doStartTag] - No message found under code 'isAutoReminderEnabled_tip' for locale 'en_US'.
javax.servlet.jsp.JspTagException: No message found under code 'isAutoReminderEnabled_tip' for locale 'en_US'.

**Comment by MNABIL89** [comment]
The same, Any Update?

**Comment by MNABIL89** [comment]
Just Add The messages in Message.properties

isSocrataPublishable_tip= This Checkbox allows this survey to be published to the Socrata Portal.
isAutoReminderEnabled_tip=This Checkbox allows this survey invitation to be sent periodically.
